name: media_player
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.10.1
  permission_handler: ^12.0.1
  path: ^1.9.1
  provider: ^6.1.5+1
  audiotags: ^1.4.5
  flutter_video_info: ^1.3.3
  google_fonts: ^6.3.3
  screen_brightness: ^2.1.7
  volume_controller: ^3.4.1
  video_thumbnail: ^0.5.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

# App Branding Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/logo/logo.png"
  android_12:
    image: "assets/logo/logo.png"
    icon_background_color: "#000000"